[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y --no-install-recommends libpq-dev"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
    "npm install",
    "npm run prod"
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[build.args]
NODE_VERSION = "18"
PHP_VERSION = "8.2"

[build.environment]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
APP_KEY = "${APP_KEY}"
APP_URL = "${RAILWAY_PUBLIC_DOMAIN}"
DB_CONNECTION = "pgsql"
DB_HOST = "${DATABASE_URL}"
DB_PORT = "${DATABASE_PORT}"
DB_DATABASE = "${DATABASE_NAME}"
DB_USERNAME = "${DATABASE_USER}"
DB_PASSWORD = "${DATABASE_PASSWORD}"
